### ISSUE TITLE
新学年导入课程表无法展示验证码

### ISSUE THREAD

**Issue by wi1dcard** [idealclover/NJU-Class-Shedule-Android#27]
如图：

![image](https://user-images.githubusercontent.com/25447002/63824888-36755c00-c948-11e9-9e72-8301aebee425.png)

望修复，多谢。

**Comment by wi1dcard** [comment]
看起来似乎是因为多了一层 SSO 登录验证？

**Comment by wi1dcard** [comment]
应该就是多了一层 SSO 导致的。我尝试用中间人攻击拦截 HTTP 请求，把 SSO 登录成功返回的 Cookie（`wengine_ticket=<MANUAL_HIDDEN>; iPlanetDirectoryPro=<MANUAL_HIDDEN>`）加入到原始请求的 Cookies 里，测试可行。

**Comment by wi1dcard** [comment]
我不太懂 Android 相关开发，不过比较熟悉网络这一块。

其实应该比较好修，而且修复后对用户是无感的（不需要执行额外操作），思路如下：

1. 先到 SSO 那边发送一下登录请求
2. 拿到返回的 Cookies
3. 带上这些 Cookies，执行原有逻辑即可

不过我抓包看了一下，他的密码是经过一次加密的，整个登录逻辑大概是这样：

1. 首先请求首页（`GET http://authserver.nju.edu.cn/authserver/login?service=http://ng.nju.edu.cn/wengine-auth/login`），拿到一个看似是 CSRF Token 的东西，以备后面使用：

```
<input type="hidden" name="lt" value="LT-3858445-kNWDZeOEaVfDacHd0wekboFmdf2FFI1566991861102-2Ddo-cas"/>
```

需要的数据是 `LT-3858445-kNWDZeOEaVfDacHd0wekboFmdf2FFI1566991861102-2Ddo-cas`，可以用正则 `<input.*?name="lt"\s+value="(.+?)"` 匹配出来。

2. 在网页源代码里有一个密钥，大概长这样：

![image](https://user-images.githubusercontent.com/25447002/63850791-7e879380-c9c7-11e9-9eb5-3ee367ff923b.png)

可以用正则 `pwdDefaultEncryptSalt\s*=\s*"(\w+)"` 匹配出来。

3. 拿到这个密钥，执行 AES 加密。JS 代码在 <http://authserver.nju.edu.cn/authserver/custom/js/login-wisedu_v1.0.js>，大概长这样：

```javascript
function encryptPassword(pwd0) {
	try{
		var pwd1 = encryptAES(pwd0,pwdDefaultEncryptSalt);
		$("#casLoginForm").find("#passwordEncrypt").val(pwd1);
	}catch(e){
		$("#casLoginForm").find("#passwordEncrypt").val(pwd0);
	}
}
```

其中 `pwdDefaultEncryptSalt` 就是刚刚拿到的密钥，`pwd0` 为明文密码。

加密函数 `encryptAES` 的代码在 `http://authserver.nju.edu.cn/authserver/custom/js/encrypt/encrypt.wisedu.js`。这段代码你可以直接用 Java 执行 JavaScript，或者直接用 Java 实现一下，逻辑很简单，大概是这样的：

> 使用标准 AES 加密，CBC 模式，PKCS7 Padding；被加密数据是 **随机 64 位字符 + 明文密码字符串（UTF-8）**；密钥刚刚已经拿到，IV 是随机 16 字节的数据。
>
> 加密后的数据进行 Base64 编码即可得到加密后的密码字符串。

另外你可以参考一下 Google `cryptojs to java`，我看了下还是有不少答案的（虽然看不懂 Java）...

3. 最后，发送请求到 `http://authserver.nju.edu.cn/authserver/login?service=http://ng.nju.edu.cn/wengine-auth/login`，HTTP Method 是 POST，参数大致是：

```
username: <Username>
password: <Base64 encoded password string>
lt: <Token from the first step>
dllt: userNamePasswordLogin
execution: e1s1
_eventId: submit
rmShown: 1
```

其中 `execution` 也可以从第一步的源代码中拿到，不过我感觉（猜测）应该用 `e1s1` 固定值没什么问题。

4. 最后，如果登录成功服务器会返回 302，不成功返回 200，这样就能拿到 Cookies 了。值得注意的是，登录成功会经过多次 HTTP Redirect，每次 Redirect 都会拿到几个 Cookie，所以你可能需要开启 Okhttp 的 Auto Redirect（我简单看了下代码似乎你关掉了），或者自己实现这一部分。

登录成功之后的几个 Redirection 大概长这样：

```
HTTP/1.1 302 Moved Temporarily
Server: openresty
Date: Wed, 28 Aug 2019 11:36:53 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
Cache-Control: no-store
Pragma: no-cache
Location: http://ng.nju.edu.cn/wengine-auth/login?ticket=<HIDDEN>
Expires: Thu, 01 Jan 1970 00:00:00 GMT
SET-COOKIE: CASTGC=<HIDDEN>;Path=/authserver/;HttpOnly;
Set-Cookie: CASPRIVACY=; expires=Thu, 01-Jan-1970 01:00:00 GMT; path=/authserver/
Set-Cookie: iPlanetDirectoryPro=<HIDDEN> domain=.nju.edu.cn; path=/


HTTP/1.1 301 Moved Permanently
Server: none
Date: Wed, 28 Aug 2019 11:36:53 GMT
Content-Type: text/html
Content-Length: 177
Location: http://ng.nju.edu.cn/wengine-auth/login/?ticket=<HIDDEN>
Connection: keep-alive


HTTP/1.1 302 Found
Server: none
Date: Wed, 28 Aug 2019 11:36:53 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Cookie
Location: http://elite.nju.edu.cn
Set-Cookie: wengine_ticket=<HIDDEN>; Domain=nju.edu.cn; httponly; Path=/
```

祝好运！有问题随时问我哈。

**Comment by idealclover** [comment]
感谢！大概看明白了～
但是有个问题，就是统一认证平台的用户名和密码和教务平台的用户名和密码是不一样的，需要让用户手动输入统一认证平台的密码，没办法做到无感

**Comment by wi1dcard** [comment]
😅哦哦，哈哈，不好意思哈，是我没有了解清楚，误以为两个平台的账号密码是一致的。

期待修复！非常感谢。

**Comment by wi1dcard** [comment]
😅哦哦，哈哈，不好意思哈，是我没有了解清楚，误以为两个平台的账号密码是一致的。

期待修复！非常感谢。

**Comment by idealclover** [comment]
没关系！后续也会尝试进一步修复 BUG 和与教务处沟通！
感谢！真的帮大忙了！要不然自己抓包排查还要好一阵！～
